apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .metadata.name }}
  namespace: nvidia-network-operator
spec:
  channel: {{ .spec.channel }} 
  name: {{ .spec.name }}
  source: {{ .spec.source }}
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

